/**
 * Templates Part 1: Basic Categories
 * Includes: basic-counter, arithmetic, comparisons
 * Defines CATEGORIES constant with all 24 categories
 */

// ============================================================================
// CATEGORIES DEFINITION - All 24 Example Categories
// ============================================================================

export const CATEGORIES = [
  // MANDATORY CORE EXAMPLES (17 categories)
  {
    id: 'basic-counter',
    name: 'Basic Counter',
    description: 'Simple encrypted counter with increment/decrement operations',
    complexity: 'Beginner',
    isPro: false,
    contractName: 'BasicCounter',
    keywords: ['counter', 'increment', 'state'],
  },
  {
    id: 'arithmetic',
    name: 'Arithmetic Operations',
    description: 'Add, subtract, multiply encrypted integers',
    complexity: 'Beginner',
    isPro: false,
    contractName: 'Arithmetic',
    keywords: ['arithmetic', 'add', 'subtract', 'multiply'],
  },
  {
    id: 'comparisons',
    name: 'Comparisons',
    description: 'Greater than, less than, equal comparisons on encrypted values',
    complexity: 'Beginner',
    isPro: false,
    contractName: 'Comparisons',
    keywords: ['comparison', 'gt', 'lt', 'eq'],
  },
  {
    id: 'single-encryption',
    name: 'Single Encryption',
    description: 'User-side encryption of a single value',
    complexity: 'Beginner',
    isPro: false,
    contractName: 'SingleEncryption',
    keywords: ['encryption', 'user-side', 'single'],
  },
  {
    id: 'multiple-encryption',
    name: 'Multiple Encryption',
    description: 'Encrypt and manage multiple encrypted values',
    complexity: 'Intermediate',
    isPro: false,
    contractName: 'MultipleEncryption',
    keywords: ['encryption', 'batch', 'multiple'],
  },
  {
    id: 'single-decryption-user',
    name: 'Single Decryption (User)',
    description: 'User-authorized decryption with FHE.allow()',
    complexity: 'Intermediate',
    isPro: false,
    contractName: 'SingleDecryptionUser',
    keywords: ['decryption', 'user-authorized', 'allow'],
  },
  {
    id: 'single-decryption-public',
    name: 'Single Decryption (Public)',
    description: 'Public decryption for transparent operations',
    complexity: 'Intermediate',
    isPro: false,
    contractName: 'SingleDecryptionPublic',
    keywords: ['decryption', 'public', 'reveal'],
  },
  {
    id: 'multiple-decryption',
    name: 'Multiple Decryption',
    description: 'Decrypt multiple encrypted values efficiently',
    complexity: 'Intermediate',
    isPro: false,
    contractName: 'MultipleDecryption',
    keywords: ['decryption', 'batch', 'multiple'],
  },
  {
    id: 'access-control',
    name: 'Access Control',
    description: 'Role-based access control with encrypted permissions',
    complexity: 'Intermediate',
    isPro: false,
    contractName: 'AccessControl',
    keywords: ['access', 'roles', 'permissions'],
  },
  {
    id: 'input-verification-proofs',
    name: 'Input Verification Proofs',
    description: 'Input validation with encrypted proofs',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'InputVerificationProofs',
    keywords: ['verification', 'validation', 'proofs'],
  },
  {
    id: 'anti-patterns-guide',
    name: 'Anti-Patterns Guide',
    description: 'Educational guide showing common FHE anti-patterns',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'AntiPatternsGuide',
    keywords: ['anti-patterns', 'education', 'mistakes'],
  },
  {
    id: 'handles-lifecycle',
    name: 'Handles Lifecycle',
    description: 'Encrypted value handle lifecycle management',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'HandlesLifecycle',
    keywords: ['handles', 'lifecycle', 'management'],
  },
  {
    id: 'oz-erc20-wrapper',
    name: 'OpenZeppelin ERC20 Wrapper',
    description: 'Wrapper pattern for encrypted ERC20 balance tracking',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'OZErc20Wrapper',
    keywords: ['erc20', 'wrapper', 'token'],
  },
  {
    id: 'oz-erc7984-basic',
    name: 'OpenZeppelin ERC7984 Basic',
    description: 'Basic ERC7984 modular FHE implementation',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'OZERC7984Basic',
    keywords: ['erc7984', 'modular', 'fhe'],
  },
  {
    id: 'swaps',
    name: 'Swaps (AMM)',
    description: 'Simplified AMM with encrypted reserves',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'Swaps',
    keywords: ['dex', 'amm', 'swap'],
  },
  {
    id: 'vesting',
    name: 'Vesting',
    description: 'Token vesting with encrypted amounts',
    complexity: 'Advanced',
    isPro: false,
    contractName: 'Vesting',
    keywords: ['vesting', 'token', 'schedule'],
  },
  {
    id: 'blind-auction',
    name: 'Blind Auction',
    description: 'Private auction with encrypted bids',
    complexity: 'Expert',
    isPro: false,
    contractName: 'BlindAuction',
    keywords: ['auction', 'sealed-bid', 'privacy'],
  },

  // PRO BONUS EXAMPLES (7 categories)
  {
    id: 'dao-voting-pro',
    name: 'DAO Voting Pro',
    description: 'Advanced voting with encrypted vote counts and weights',
    complexity: 'Expert',
    isPro: true,
    contractName: 'DAOVotingPro',
    keywords: ['dao', 'voting', 'governance'],
  },
  {
    id: 'private-lending-pro',
    name: 'Private Lending Pro',
    description: 'Private lending protocol with encrypted amounts',
    complexity: 'Expert',
    isPro: true,
    contractName: 'PrivateLendingPro',
    keywords: ['lending', 'loan', 'collateral'],
  },
  {
    id: 'blind-dex-pro',
    name: 'Blind DEX Pro',
    description: 'Advanced DEX with MEV-resistant encrypted order books',
    complexity: 'Expert',
    isPro: true,
    contractName: 'BlindDEXPro',
    keywords: ['dex', 'orderbook', 'mev'],
  },
  {
    id: 'poker-game-pro',
    name: 'Poker Game Pro',
    description: 'Private poker game with encrypted hands',
    complexity: 'Expert',
    isPro: true,
    contractName: 'PokerGamePro',
    keywords: ['poker', 'game', 'private'],
  },
  {
    id: 'yield-farming-pro',
    name: 'Yield Farming Pro',
    description: 'Private yield farming with encrypted stake amounts',
    complexity: 'Expert',
    isPro: true,
    contractName: 'YieldFarmingPro',
    keywords: ['yield', 'farming', 'rewards'],
  },
  {
    id: 'mev-arbitrage-pro',
    name: 'MEV Arbitrage Pro',
    description: 'MEV-resistant arbitrage with encrypted price feeds',
    complexity: 'Expert',
    isPro: true,
    contractName: 'MEVArbitragePro',
    keywords: ['mev', 'arbitrage', 'dex'],
  },
  {
    id: 'confidential-stablecoin-pro',
    name: 'Confidential Stablecoin Pro',
    description: 'Privacy-preserving stablecoin with encrypted collateral',
    complexity: 'Expert',
    isPro: true,
    contractName: 'ConfidentialStablecoinPro',
    keywords: ['stablecoin', 'collateral', 'privacy'],
  },
];

// ============================================================================
// BASIC COUNTER CONTRACT (Part 1.1)
// ============================================================================

